# Generated by Django 5.0.4 on 2025-02-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_managers'),
        ('users', '0004_alter_customuser_managers_child'),
    ]

    operations = [
    ]
