# Generated by Django 5.0.4 on 2025-03-18 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20250221_1245'),
        ('users', '006_replace_activities_with_interests'),
    ]

    operations = [
    ]
