# Generated by Django 5.0.4 on 2025-06-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location_preferences',
            field=models.JSONField(default=list, help_text="User's preferred locations for recommendations (zip codes)"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='search_history_locations',
            field=models.JSONField(default=list, help_text='Historical locations user has searched (zip codes)'),
        ),
    ]
