# Generated by Django 5.0.4 on 2025-06-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_location_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='homebaseZipCode',
            field=models.CharField(blank=True, help_text="User's primary/home zip code for personalized recommendations", max_length=10, null=True),
        ),
    ]
