# Generated by Django 5.0.4 on 2025-07-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_trial_active',
            field=models.BooleanField(default=False, help_text='Whether user is currently in free trial'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, help_text='When the free trial ends', null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, help_text='When the free trial started', null=True),
        ),
    ]
