# Generated by Django 5.0.4 on 2025-05-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('place_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('data_id', models.CharField(blank=True, max_length=255, null=True)),
                ('reviews_link', models.URLField(blank=True, max_length=1024, null=True)),
                ('photos_link', models.URLField(blank=True, max_length=1024, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('types', models.JSONField(blank=True, default=list)),
                ('address', models.TextField(blank=True, null=True)),
                ('extensions', models.JSONField(blank=True, default=dict)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('formatted_address', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('hours', models.JSONField(blank=True, default=dict)),
                ('place_images', models.JSONField(blank=True, default=list)),
                ('reviews_list', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'ordering': ['title'],
            },
        ),
    ]
