# Generated by Django 5.0.4 on 2025-05-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurtrDjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='popular_times',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='reviews_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
