# Generated by Django 5.0.4 on 2025-05-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurtrDjango', '0002_place_popular_times_alter_place_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
