# Generated by Django 5.0.4 on 2025-06-05 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurtrDjango', '0003_place_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateField(help_text='Date these recommendations were generated')),
                ('user_profile_hash', models.CharField(help_text='Hash of user profile for cache invalidation', max_length=64)),
                ('recommendations', models.JSONField(help_text='Daily aggregated recommendation results (up to 15)')),
                ('custom_queries', models.JSONField(help_text='Generated search queries used')),
                ('locations_searched', models.JSONField(help_text='List of locations searched for these recommendations')),
                ('total_results', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Daily Recommendation',
                'verbose_name_plural': 'User Daily Recommendations',
                'ordering': ['-date_generated', '-updated_at'],
                'unique_together': {('user', 'date_generated')},
            },
        ),
    ]
