# Generated by Django 5.0.4 on 2025-06-09 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurtrDjango', '0004_userrecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecommendation',
            name='recommendations',
        ),
        migrations.CreateModel(
            name='UserRecommendationPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalization_score', models.IntegerField(default=0, help_text="How well this place matches the user's profile")),
                ('searched_location', models.CharField(help_text='Which location search found this place', max_length=255)),
                ('source_query', models.TextField(help_text='Which search query found this place')),
                ('recommendation_rank', models.IntegerField(help_text='Rank of this place in the recommendation list (1=best)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NurtrDjango.place')),
                ('user_recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NurtrDjango.userrecommendation')),
            ],
            options={
                'verbose_name': 'User Recommendation Place',
                'verbose_name_plural': 'User Recommendation Places',
                'ordering': ['recommendation_rank'],
                'unique_together': {('user_recommendation', 'place')},
            },
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='recommended_places',
            field=models.ManyToManyField(related_name='user_recommendations', through='NurtrDjango.UserRecommendationPlace', to='NurtrDjango.place'),
        ),
    ]
