# Generated by Django 5.0.4 on 2025-06-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurtrDjango', '0006_event_alter_userrecommendation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecommendationevent',
            name='personalized_explanation',
            field=models.TextField(blank=True, help_text='AI-generated explanation for why this event was recommended', null=True),
        ),
        migrations.AddField(
            model_name='userrecommendationplace',
            name='personalized_explanation',
            field=models.TextField(blank=True, help_text='AI-generated explanation for why this place was recommended', null=True),
        ),
    ]
